#!/usr/bin/env python

RUN_TIME_LIMIT = 600 #Seconds
OPERATION_TIME_LIMIT = 15 #Seconds

NUMBER_OF_VIEWPOINTS = 13
LAST_VIEWPOINT = 12

SHUFFLE_COUNTER_MAX = 3
DIP_COUNTER_MAX = 3
DIP_TIME_LIMIT = 10 #Seconds

VISION_LOOK_TIME = 0#Seconds
STARE_TIME = 1 #Second


SPEED_SCALE = 0.1

