#!/usr/bin/env python

RUN_TIME_LIMIT = 600 #Seconds
OPERATION_TIME_LIMIT = 15 #Seconds

NUMBER_OF_VIEWPOINTS = 4

SHUFFLE_COUNTER_MAX = 3
DIP_COUNTER_MAX = 3
DIP_TIME_LIMIT = 10 #Seconds

VISION_LOOK_TIME = 0#Seconds


SPEED_SCALE = 0.05

